# Site settings
title: "My Awesome Blog"
email: you@example.com
description: "Thoughts, tutorials, and musings."
baseurl: ""                # leave empty for user.github.io
url: "https://stoltzmaniac.github.io"

# Theme & pagination
theme: minima
paginate: 5                # posts per page

# Optional: enable future posts if you like drafts published later
future: true
