# .github/workflows/gh-pages.yml
name: Build & Deploy Jekyll Site

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out your repo
        uses: actions/checkout@v3

      - name: Set up Ruby & Bundler cache
        uses: ruby/setup-ruby@v1
        with:
          # match your Gemfile’s Ruby version
          ruby-version: 3.1  
          bundler-cache: true   # runs `bundle install` + caches gems

      - name: Build the site with Jekyll
        # this will use the gems you just installed
        uses: actions/jekyll-build-pages@v1

      # Optional: deploy to GitHub Pages if you want
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
